[book]
authors = ["Ryan Parsley"]
language = "en"
multilingual = false
src = "src"
title = "mdBook Test"

[preprocessor.yml-header]

[preprocessor.cmdrun]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
no-section-label = true
additional-js = ["mermaid.min.js", "mermaid-init.js"]
